<a href="https://colab.research.google.com/github/AamirAli310/Python-Basics/blob/main/Assignment_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Assignment Task # 3 (About Matrices)**
**Task Detail**: Consider the 3x3 matrix A, given by:

A =

1.	Calculate the inverse of matrix A, denoted as A-1.
2.	Show that A * A-1 = A-1 * A = I, where I is the 3x3 identity matrix.


In [ ]:
#Importing Numpy lib to create & perform required task
import numpy as np #given alias np

#defining a Matrix & referance it in variable named Mat_A using np.array function
Mat_A = np.array([[2,3,5],[1,-4,2],[3,1,-1]])
print("Matrix Mat_A : \n", Mat_A)

#____________________________________________________________#
#TASK 3_1.	Calculate the inverse of matrix A, denoted as A-1:
#_____________________SOLUTION_______________________________#
#____We'll find determinant of A first, If it's non-zero then#
#____proceed for Inverse of Mat_A____________________________#

#Using numpy Linear Algebra function DET to find determinant of Mat A:
Det_Mat_A = np.linalg.det(Mat_A)

#Checked if Determinant is Zero or NOT
if(Det_Mat_A != 0): #So we can proceed for Inverse of matrix now.
  print("\n\n Determinant of Mat_A is :\n", Det_Mat_A)

  #Finding inverse of Mat_A using numpy linear Algebra fun INV
  Inv_Mat_A = np.linalg.inv(Mat_A)
  print("\n\n Inverse of Mat_A is: \n",Inv_Mat_A)

  #________________________________________________________________________________#
  #TASK 3_2.	Show that A * A-1 = A-1 * A = I, where I is the 3x3 identity matrix.:
  #___________________________________SOLUTION_____________________________________#
  #____We've already Matrix A & Inverse of Mat_A. So we'll use Numpy Dot function  #
  #_to multiply Mat_A with Inv_Mat_A & save resultant Matrix in LHS_A and RHS_A____#

  #Multiply Mat_A with Invrse of Mat_A using Numpy DOT function & storing resultant matrix in LHS_A
  LHS_A = np.dot(Mat_A,Inv_Mat_A)
  print("\n\n Mat_A * Inv_Mat_A = \n", LHS_A)

  #Multiply Invrse of Mat_A with Mat_A using Numpy DOT function & storing resultant matrix in RHS_A
  RHS_A = np.dot(Inv_Mat_A,Mat_A)
  print("\n\n Inv_Mat_A * Mat_A = \n", RHS_A)

  #Evaluation of LHS_A & RHS_A are Identity matrix OR Not using Numpy EYE function
  Is_LHS_Identity_Matrix = np.allclose(LHS_A, np.eye(3))
  Is_RHS_Identity_Matrix = np.allclose(RHS_A, np.eye(3))

  if(Is_LHS_Identity_Matrix & Is_RHS_Identity_Matrix):
    print("\n Hence Prove Mat_A*Inv_Mat_A = Inv_Mat_A*Mat_A = I")
  elif(Is_LHS_Identity_Matrix == False & Is_RHS_Identity_Matrix == False):
    print("\n Mat_A*Inv_Mat_A & Inv_Mat_A*Mat_A both are NOT IDENTITY Matrix")
  elif(Is_LHS_Identity_Matrix == False):
   print("\n Mat_A*Inv_Mat_A is not IDENTITY Matrix")
  elif(Is_RHS_Identity_Matrix == False):
   print("\n Inv_Mat_A*Mat_A is not IDENTITY Matrix")
else:
  print("Sorry Mat_A Determinant is '0', Hence It's Inverse not possible.")


Matrix Mat_A : 
 [[ 2  3  5]
 [ 1 -4  2]
 [ 3  1 -1]]


 Determinant of Mat_A is :
 90.0


 Inverse of Mat_A is: 
 [[ 0.02222222  0.08888889  0.28888889]
 [ 0.07777778 -0.18888889  0.01111111]
 [ 0.14444444  0.07777778 -0.12222222]]


 Mat_A * Inv_Mat_A = 
 [[ 1.00000000e+00 -5.55111512e-17  2.77555756e-17]
 [-5.55111512e-17  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  2.77555756e-17  1.00000000e+00]]


 Inv_Mat_A * Mat_A = 
 [[ 1.00000000e+00 -1.11022302e-16  0.00000000e+00]
 [-8.67361738e-18  1.00000000e+00 -4.33680869e-17]
 [ 2.77555756e-17 -2.77555756e-17  1.00000000e+00]]

 Hense Prove Mat_A*Inv_Mat_A = Inv_Mat_A*Mat_A = I
