<a href="https://colab.research.google.com/github/AamirAli310/Python-Basics/blob/main/Assignment_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Python Basic - Assignment

**Task 1: [50 Marks] – Report Format (Solution, Output & Explanation)**
***Supermarket Inventory Management System***
Create a Python program that manages a supermarket's inventory. The inventory should include product details such as product name, product category, product ID, quantity in stock, and price per unit. The system should be able to perform the following operations:
1.	**Add a New Product **(20 points)
●	The user should be able to add a new product to the inventory. Validate that the product ID is unique and the quantity and price are positive numbers. If any of these conditions are not met, show an appropriate error message.
2.	**Update a Product's Details** (10 points)
●	The user should be able to update the details of a product. If the product does not exist, display an appropriate error message.
3.	**Search for a Product **(10 points)
●	The user should be able to search for a product using the product name or product ID.
4.	**Display All Products **(10 points)
●	Display all the products in the inventory sorted by product name. Each product should be displayed with all its details.

Please include at least one function for each operation. Include appropriate comments in your code, demonstrating the use of comments in programming.
Remember to use appropriate data structures to store your data. Consider using a dictionary where the key is the product ID and the value is another dictionary with keys for the product name, product category, quantity, and price.


In [3]:
#A&A Inventory Management System created by Aamir Ali on 23/12/2024
#Global variable to store all stock
AA_SI = {
    "1":{
        'Id':1,
        'Name':"Al Marai Yougart",
        'Category':"Dairy",
        'Unit':"KG",
        'Price':8.0,
        'Quantity':1000
    },
    "2":{
        'Id':2,
        'Name':"Al Rawabi Yougart",
        'Category':"Dairy",
        'Unit':"KG",
        'Price':7.0,
        'Quantity':600
    },
    "3":{
      'Id':3,
      'Name':"Yummy Bread Large",
      'Category':"Bakery",
      'Unit':"Pack",
      'Price':5.25,
      'Quantity':100
    },
    "4":{
      'Id':4,
      'Name':"Golden Milky Bread Large",
      'Category':"Bakery",
      'Unit':"Pack",
      'Price':6.25,
      'Quantity':300
    }
}

#************ MY UTILITY FUNCTIONS START ***************

#Function to return a sorted list of products by Product Names with Semi-colon Product ID:
def getSortedByNameID():
  #print("In getSortedByNameID function");
  sortedProducts = [];
  #Looping on all items of AA_SI dictionary
  for pID, product in AA_SI.items():#pID is first key and product is object link with pID key
    #print("Product ID: ", pID);
    #print("Product Obj: ", product);
    nameKey = product['Name']+":"+pID;
    sortedProducts.append(nameKey);
  #Sorting products using built-in function sort
  sortedProducts.sort();
  return sortedProducts;

#function to take user inputs as per user message & data type
def getUserInput(message, type):
  userInput = type(input(message));
  return userInput;

#Function to return sorted list of product Names only:
def getSortedByName():
  sortedProducts = [];
  #Looping on all items of AA_SI dictionary
  for pID, product in AA_SI.items():#pID is first key and product is object link with pID key
    #Only taken product name & append to the list (Todos: Duplicate name should be checked but by passing as it's out of scope)
    sortedProducts.append(product['Name']);
  #Sorting products using built-in function sort
    sortedProducts.sort();
  return sortedProducts;


#Function to print all keys of a product dynamically
def printProduct(product):
  #For loop on Product's keys array
 for key in product.keys():
  if len(key) > 4:
    print("Product ", key, ":\t",product[key]);
  else:
      print("Product ", key, ":\t\t",product[key])
 print("\n-----------------------------");

#************ MY UTILITY FUNCTIONS END ***************


#*Display All Products *(10 points) ●
#Display all the products in the inventory sorted by product name.
#Each product should be displayed with all its details.

#Function to display all inventory of the supermarket
def displayInventory():
  #First get all product sorted by Names along with Product ID
  sortedProducts = getSortedByNameID()
  print("----------------------------------------");
  print("--A&A INVENTORY PRODUCTS ORDER BY NAME--");
  print("----------------------------------------");
  for sprod in sortedProducts:#Looping to display each product
    #Logict to split ID from product name
    pID = sprod.split(":")[1];
    #Got Product object by Product ID
    product = AA_SI[pID];
    #Pass product to my print function
    printProduct(product)

#*Add a New Product *(20 points) ●
#The user should be able to add a new product to the inventory.
#Validate that the product ID is unique and the quantity and price are positive numbers.
#If any of these conditions are not met, show an appropriate error message.
def addNewProduct():
  print("You're going to add new product in A&A Inventory");
  print("\nPlease provide input according to the policy");
  #as product name, product category, product ID, quantity in stock, and price per unit.
  #Made a list from Keys
  allPIDs = list(AA_SI.keys());
  lastPID = allPIDs[-1];#taken last element from the ID's list
  productID = getUserInput("Enter an Unique Product ID (Last product ID is: "+lastPID+") \n", str);
  #Validating if product id unique or not
  while productID in allPIDs: #Using while loop for condition to re-take input from the user until unique Product ID is entered
    print("Product ID:",productID,"Already exist, Please try again.");
    productID = getUserInput("Enter an Unique Product ID (Last product ID is: "+lastPID+") \t", str);

  pName = getUserInput("Enter Product Name:\t", str);
  pCategory = getUserInput("Enter Product Category:\t", str);
  pQuantity = getUserInput("Enter Product Quantity:\t", int);

   #Verifying Product Quantity only positive number
  while pQuantity < 0: #Using while loop for condition to re-take input from the user until a postive number is entered
    print("Product Quantity cannot be a negative number, Please try again.");
    pQuantity = getUserInput("Enter Product Quantity:\t", int);
  pUnit = getUserInput("Enter Product Unit(G,KG,ML,Liters):\t", str);
  pUnitPrice = getUserInput("Enter Product Price:\t", float);
  #Verifying Product price only positive number
  while pUnitPrice < 0: #Using while loop for condition to re-take input from the user until a postive number is entered
    print("Price cannot be a negative number, Please try again.");
    pUnitPrice = getUserInput("Enter Product Price:\t", float);

  #If control reached here it means we're good to go & add this product into A&A Inventory Dictionary
  AA_SI[productID] = {
      'Id':productID,
      'Name':pName,
      'Category':pCategory,
      'Unit':pUnit.upper(),
      'Price':pUnitPrice,
      'Quantity':pQuantity
  }
  print("Product Added Successfully \n");
  displayInventory();

#Update a Product's Details (10 points)
#● The user should be able to update the details of a product.
#If the product does not exist, display an appropriate error message.
def updateAProduct():
  print("You're going to update a product in A&A Inventory");
  matchedProductID = findAProduct(False);
  if(matchedProductID != -1):
    print("Here are Product Details: \n");
    printProduct(AA_SI[matchedProductID]);
    userAction = getUserInput("Do you want to update it?", bool);
    if userAction:
      pName = getUserInput("Enter New Product Name:\t", str);
      pCategory = getUserInput("Enter New Product Category:\t", str);
      pQuantity = getUserInput("Enter New Product Quantity:\t", int);

      #Verifying Product Quantity only positive number
      while pQuantity < 0: #Using while loop for condition to re-take input from the user until a postive number is entered
        print("New Product Quantity cannot be a negative number, Please try again.");
        pQuantity = getUserInput("Enter New Product Quantity:\t", int);
      pUnit = getUserInput("Enter New Product Unit(G,KG,ML,Liters):\t", str);
      pUnitPrice = getUserInput("Enter New Product Price:\t", float);
      #Verifying Product price only positive number
      while pUnitPrice < 0: #Using while loop for condition to re-take input from the user until a postive number is entered
        print("Price cannot be a negative number, Please try again.");
        pUnitPrice = getUserInput("Enter New Product Price:\t", float);

      AA_SI[matchedProductID] = {
          'Id':matchedProductID,
          'Name':pName,
          'Category':pCategory,
          'Unit':pUnit.upper(),
          'Price':pUnitPrice,
          'Quantity':pQuantity
      };

      displayInventory();
      print("Product Updated Successfully \n");
    else:
      print("Product Update Cancelled By User.");
  else:
    print("Sorry Product ",subMsg, userInput, " doesn't exist");


#*Search for a Product *(10 points)
#● The user should be able to search for a product using
#the product name or product ID.
def findAProduct(displayMessage):
  matchedProductID = -1;
  subMsg = "";
  if displayMessage == True:
    print("You're going to search a product in A&A Inventory");

  userInput = getUserInput("Enter Product Name or Product ID:\t", str);
  #If input contains only numbers it, Search by Product ID
  if userInput.isnumeric():
    #Created a list copy from keys
    productIDs = list(AA_SI.keys());
    subMsg = "ID";
    if userInput in productIDs:
      matchedProductID = userInput;
  elif not userInput.isnumeric():
    #Means user wants searcy by product name
    sortedProducts = getSortedByNameID();
    #Looping each product from the list
    for product in sortedProducts:
      #Making user input to lower case
      userInput = userInput.lower();
      #Spliting product & product id
      pParts = product.split(":");
      #Got product name & converted to same lower case to match with user input
      product = (pParts[0]).lower();
      #Product ID stored to be use later
      prodID = pParts[1];

      if product.find(userInput) != -1 or product.startswith(userInput):
        matchedProductID = prodID;#Taken product ID out from Product name
        break;
  else:
    print("Sorry Invalid Input");

  #If Find function called within Update function then it needs to return Product ID
  if displayMessage == False:
    return matchedProductID;
  elif matchedProductID != -1:
    print("Product Found Successfully \n");
    printProduct(AA_SI[matchedProductID]);
  else:
    print("Sorry Requested Product",subMsg, userInput, " Not Found");
    return;

def main():

  #addNewProduct();
  #findAProduct(True);
  #updateAProduct();
  displayInventory();

#Execute complete program by calling main function
main();

You're going to search a product in A&A Inventory
Enter Product Name or Product ID:	Flower
Sorry Requested Product  flower  Not Found


**Task 2: [20 Marks] – Report Format (Solution, Output & Explanation)
Function Development**

1.	Create a function called "calculate_discount," which takes in a parameter "amount" and returns the discounted amount after applying a discount of 10%. [10 Marks]
2.	Create a function called "calculate_net_amount," which takes in three parameters: "amount," "discount," and "tax." The function should calculate the net amount after applying the discount and adding the tax. [10 Marks]


In [ ]:
#1.Create a function called "calculate_discount,"
#which takes in a parameter "amount" and returns the discounted amount
#after applying a discount of 10%. [10 Marks]
def calculate_discount(amount):
  #First get all product sorted by Names along with Product ID
  discountPrice = amount - (amount*0.1); #10/100 = 0.1 that means 10% discount
  return discountPrice;

#2.Create a function called "calculate_net_amount,"
# which takes in three parameters: "amount," "discount," and "tax."
#The function should calculate the net amount after applying the discount
#and adding the tax. [10 Marks]
def calculate_net_amount(amount, discount, tax):
  #Calculated discounted price through given discount percentage
  if discount > 1:
    discount = discount / 100; # Converting discount into percentage out of 100

  discountedPrice = amount - (amount*discount); #Considering discount value will be in percentage always
  #Simply adding Tax into discounted amount
  netAmountWithTax = discountedPrice + tax;
  return netAmountWithTax;

def mainTask2():
  #discountedAmount = calculate_discount(190.50);
  #print("10% Discounted amount of 190.50 is \n", discountedAmount);

  netAmount = calculate_net_amount(190.50, 25, 5)#finding net amount with 25% discount an 5$ Tax
  print("If Unit amount is 190.50 with 25% discount and 5$ Tax \n Net Amount is:",netAmount);


mainTask2();

If Unit amount is 190.50 with 25% discount and 5$ Tax 
 Net Amount is: 147.875


**Task # 3 (About Matrices)**
**Task Detail**: Consider the 3x3 matrix A, given by:

A =

1.	Calculate the inverse of matrix A, denoted as A-1.
2.	Show that A * A-1 = A-1 * A = I, where I is the 3x3 identity matrix.


In [ ]:
#Importing Numpy lib to create & perform required task
import numpy as np #given alias np

#defining a Matrix & referance it in variable named Mat_A using np.array function
Mat_A = np.array([[2,3,5],[1,-4,2],[3,1,-1]])
print("Matrix Mat_A : \n", Mat_A)

#____________________________________________________________#
#TASK 3_1.	Calculate the inverse of matrix A, denoted as A-1:
#_____________________SOLUTION_______________________________#
#____We'll find determinant of A first, If it's non-zero then#
#____proceed for Inverse of Mat_A____________________________#

#Using numpy Linear Algebra function DET to find determinant of Mat A:
Det_Mat_A = np.linalg.det(Mat_A)

#Checked if Determinant is Zero or NOT
if(Det_Mat_A != 0): #So we can proceed for Inverse of matrix now.
  print("\n\n Determinant of Mat_A is :\n", Det_Mat_A)

  #Finding inverse of Mat_A using numpy linear Algebra fun INV
  Inv_Mat_A = np.linalg.inv(Mat_A)
  print("\n\n Inverse of Mat_A is: \n",Inv_Mat_A)

  #________________________________________________________________________________#
  #TASK 3_2.	Show that A * A-1 = A-1 * A = I, where I is the 3x3 identity matrix.:
  #___________________________________SOLUTION_____________________________________#
  #____We've already Matrix A & Inverse of Mat_A. So we'll use Numpy Dot function  #
  #_to multiply Mat_A with Inv_Mat_A & save resultant Matrix in LHS_A and RHS_A____#

  #Multiply Mat_A with Invrse of Mat_A using Numpy DOT function & storing resultant matrix in LHS_A
  LHS_A = np.dot(Mat_A,Inv_Mat_A)
  print("\n\n Mat_A * Inv_Mat_A = \n", LHS_A)

  #Multiply Invrse of Mat_A with Mat_A using Numpy DOT function & storing resultant matrix in RHS_A
  RHS_A = np.dot(Inv_Mat_A,Mat_A)
  print("\n\n Inv_Mat_A * Mat_A = \n", RHS_A)

  #Evaluation of LHS_A & RHS_A are Identity matrix OR Not using Numpy EYE function
  Is_LHS_Identity_Matrix = np.allclose(LHS_A, np.eye(3))
  Is_RHS_Identity_Matrix = np.allclose(RHS_A, np.eye(3))

  if(Is_LHS_Identity_Matrix & Is_RHS_Identity_Matrix):
    print("\n Hence Prove Mat_A*Inv_Mat_A = Inv_Mat_A*Mat_A = I")
  elif(Is_LHS_Identity_Matrix == False & Is_RHS_Identity_Matrix == False):
    print("\n Mat_A*Inv_Mat_A & Inv_Mat_A*Mat_A both are NOT IDENTITY Matrix")
  elif(Is_LHS_Identity_Matrix == False):
   print("\n Mat_A*Inv_Mat_A is not IDENTITY Matrix")
  elif(Is_RHS_Identity_Matrix == False):
   print("\n Inv_Mat_A*Mat_A is not IDENTITY Matrix")
else:
  print("Sorry Mat_A Determinant is '0', Hence It's Inverse not possible.")


Matrix Mat_A : 
 [[ 2  3  5]
 [ 1 -4  2]
 [ 3  1 -1]]


 Determinant of Mat_A is :
 90.0


 Inverse of Mat_A is: 
 [[ 0.02222222  0.08888889  0.28888889]
 [ 0.07777778 -0.18888889  0.01111111]
 [ 0.14444444  0.07777778 -0.12222222]]


 Mat_A * Inv_Mat_A = 
 [[ 1.00000000e+00 -5.55111512e-17  2.77555756e-17]
 [-5.55111512e-17  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  2.77555756e-17  1.00000000e+00]]


 Inv_Mat_A * Mat_A = 
 [[ 1.00000000e+00 -1.11022302e-16  0.00000000e+00]
 [-8.67361738e-18  1.00000000e+00 -4.33680869e-17]
 [ 2.77555756e-17 -2.77555756e-17  1.00000000e+00]]

 Hense Prove Mat_A*Inv_Mat_A = Inv_Mat_A*Mat_A = I
