<a href="https://colab.research.google.com/github/AamirAli310/Python-Basics/blob/main/Working_with_Materices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
m1=np.array([[1,2,3],[3,4,5],[7,8,9]])
print("Matrix M1: \n",m1)

Matrix M1: 
 [[1 2 3]
 [3 4 5]
 [7 8 9]]


In [13]:
import numpy as np

mat_A=np.array([[1,2,3],[4,5,6],[7,2,9]])

print("Matrix A: \n",mat_A)


med = np.median(mat_A)
print(med)

m1_multiplication = np.dot(mat_A,mat_A)
print("M1 Multiplcation: \n",m1_multiplication)

det_mat_A = np.linalg.det(mat_A)

print("M1 Determinent: \n",det_mat_A)

rev_mat_A = np.linalg.inv(mat_A)
print("Mat 1 Inverse is: \n", rev_mat_A)

Matrix M1: 
 [[1 2 3]
 [3 4 5]
 [7 8 9]]
4.0
M1 Multiplcation: 
 [[ 28  34  40]
 [ 50  62  74]
 [ 94 118 142]]
M1 Determinent: 
 -36.0
Mat 1 Inverse is: 
 [[-0.91666667  0.33333333  0.08333333]
 [-0.16666667  0.33333333 -0.16666667]
 [ 0.75       -0.33333333  0.08333333]]
